New-Item -ItemType Directory -Force -Path ../hpcc-systems/bionic

Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-platform-community_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/platform/hpccsystems-platform-community_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-couchbaseembed_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-couchbaseembed_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-javaembed_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-javaembed_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-kafka_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-kafka_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-memcached_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-memcached_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-mysqlembed_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-mysqlembed_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-redis_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-redis_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-rembed_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-rembed_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-spark_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-spark_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-sqlite3embed_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-sqlite3embed_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-sqs_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-sqs_7.2.14-1bionic_amd64.deb
Invoke-WebRequest -OutFile ../hpcc-systems/bionic/hpccsystems-plugin-v8embed_7.2.14-1bionic_amd64.deb https://d2wulyp08c6njk.cloudfront.net/releases/CE-Candidate-7.2.14/bin/plugins/hpccsystems-plugin-v8embed_7.2.14-1bionic_amd64.deb